---
title: "List of distributions implemented in extraDistr"
author: "Tymoteusz Wolodzko"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Name | Functions |  Suffix   |  Comment
---------------|---------------|---------------|---------------
Bernoulli                       | d,p,q,r   | bern      |
Beta (reparametrized)           | d,p,q,r   | prop      | parametrized by mean and precission
Beta-Binomial                   | d,p,r     | bbinom    |
Beta-Negative Binomial          | d,p,r     | bnbinom   |
Bhattacharjee                   | d,p,r     | bhatt     | normal + uniform
Birnbaum-Saunders (fatigue life)| d,p,q,r   | fatigue   |
Bivariate normal                | d,r       | bvnorm    |
Bivariate Poisson               | d,r       | bvpois    |
Categorical                     | d,p,q,r   | cat       |
Dirichlet                       | d,r       | dirichlet |
Discrete normal                 | d,p,q,r   | dnorm     |
Discrete uniform                | d,p,q,r   | dunif     |
Discrete Weibull (type I)       | d,p,q,r   | dweibull  |
Frechet                         | d,p,q,r   | frechet   |
Gamma-Poisson                   | d,p,r     | gpois     |
Generalized Extreme Value       | d,p,q,r   | gev       |
Gompertz                        | d,p,q,r   | gompertz  |
Generalized Pareto              | d,p,q,r   | gpd       |
Gumbel                          | d,p,q,r   | gumbel    |
Half-Cauchy                     | d,p,q,r   | hcauchy   |
Half-normal                     | d,p,q,r   | hnorm     |
Half-t                          | d,p,q,r   | ht        |
"Huber density"                 | d,p,q,r   | huber     | related to Huber loss
Inverse chi-squared             | d,p,q,r   | invchisq  |
Scaled inverse chi-squared      | d,p,q,r   | invchisq  |
Inverse-gamma                   | d,p,q,r   | invgamma  |
Kumaraswamy                     | d,p,q,r   | kumar     |
Laplace                         | d,p,q,r   | laplace   |
Logarythmic series              | d,p,q,r   | lgser     |
Lomax                           | d,p,q,r   | lomax     |
Mixture of normal               | d,p,r     | mixnorm   |
Mixture of Poisson              | d,p,r     | mixpois   |
Multinomial                     | d,r       | mnom      |
Multivariate hypergeometric     | d,r       | mvhyper   |
Non-standard beta               | d,p,q,r   | nsbeta    | beta with additional upper and lower bound parameters
Non-standard t                  | d,p,q,r   | nst       | t with additional parameters for location and scale
Pareto                          | d,p,q,r   | pareto    |
Power                           | d,p,q,r   | power     |
Rayleigh                        | d,p,q,r   | rayleigh  |
Skellam                         | d,r       | skellam   |
Slash                           | d,p,r     | slash     | normal/uniform    
Triangular                      | d,p,q,r   | triang    |
Truncated normal                | d,p,q,r   | tnorm     |
Truncated Poisson               | d,p,q,r   | tpois     |
Wald (inverse Gaussian)         | d,p,q,r   | wald      |
Zero-inflated binomial          | d,p,q,r   | zib       |
Zero-inflated negative binomial | d,p,q,r   | zinb      |
Zero-inflated Poisson           | d,p,q,r   | zip       |


