# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dbern <- function(x, prob, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbern', PACKAGE = 'extraDistr', x, prob, log_prob)
}

cpp_pbern <- function(x, prob, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pbern', PACKAGE = 'extraDistr', x, prob, lower_tail, log_prob)
}

cpp_qbern <- function(p, prob, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qbern', PACKAGE = 'extraDistr', p, prob, lower_tail, log_prob)
}

cpp_rbern <- function(n, prob) {
    .Call('extraDistr_cpp_rbern', PACKAGE = 'extraDistr', n, prob)
}

cpp_dbbinom <- function(x, size, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, log_prob)
}

cpp_pbbinom <- function(x, size, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pbbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, lower_tail, log_prob)
}

cpp_rbbinom <- function(n, size, alpha, beta) {
    .Call('extraDistr_cpp_rbbinom', PACKAGE = 'extraDistr', n, size, alpha, beta)
}

cpp_dbnbinom <- function(x, size, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbnbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, log_prob)
}

cpp_pbnbinom <- function(x, size, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pbnbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, lower_tail, log_prob)
}

cpp_rbnbinom <- function(n, size, alpha, beta) {
    .Call('extraDistr_cpp_rbnbinom', PACKAGE = 'extraDistr', n, size, alpha, beta)
}

cpp_dbhatt <- function(x, mu, sigma, a, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbhatt', PACKAGE = 'extraDistr', x, mu, sigma, a, log_prob)
}

cpp_pbhatt <- function(x, mu, sigma, a, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pbhatt', PACKAGE = 'extraDistr', x, mu, sigma, a, lower_tail, log_prob)
}

cpp_rbhatt <- function(n, mu, sigma, a) {
    .Call('extraDistr_cpp_rbhatt', PACKAGE = 'extraDistr', n, mu, sigma, a)
}

cpp_dfatigue <- function(x, alpha, beta, mu, log_prob = FALSE) {
    .Call('extraDistr_cpp_dfatigue', PACKAGE = 'extraDistr', x, alpha, beta, mu, log_prob)
}

cpp_pfatigue <- function(x, alpha, beta, mu, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pfatigue', PACKAGE = 'extraDistr', x, alpha, beta, mu, lower_tail, log_prob)
}

cpp_qfatigue <- function(p, alpha, beta, mu, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qfatigue', PACKAGE = 'extraDistr', p, alpha, beta, mu, lower_tail, log_prob)
}

cpp_rfatigue <- function(n, alpha, beta, mu) {
    .Call('extraDistr_cpp_rfatigue', PACKAGE = 'extraDistr', n, alpha, beta, mu)
}

cpp_dbnorm <- function(x, y, mu1, mu2, sigma1, sigma2, rho, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbnorm', PACKAGE = 'extraDistr', x, y, mu1, mu2, sigma1, sigma2, rho, log_prob)
}

cpp_rbnorm <- function(n, mu1, mu2, sigma1, sigma2, rho) {
    .Call('extraDistr_cpp_rbnorm', PACKAGE = 'extraDistr', n, mu1, mu2, sigma1, sigma2, rho)
}

cpp_dbpois <- function(x, y, a, b, c, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbpois', PACKAGE = 'extraDistr', x, y, a, b, c, log_prob)
}

cpp_dcat <- function(x, prob, log_prob = FALSE) {
    .Call('extraDistr_cpp_dcat', PACKAGE = 'extraDistr', x, prob, log_prob)
}

cpp_pcat <- function(x, prob, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pcat', PACKAGE = 'extraDistr', x, prob, lower_tail, log_prob)
}

cpp_qcat <- function(p, prob, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qcat', PACKAGE = 'extraDistr', p, prob, lower_tail, log_prob)
}

cpp_rcat <- function(n, prob) {
    .Call('extraDistr_cpp_rcat', PACKAGE = 'extraDistr', n, prob)
}

cpp_ddirichlet <- function(x, alpha, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddirichlet', PACKAGE = 'extraDistr', x, alpha, log_prob)
}

cpp_rdirichlet <- function(n, alpha) {
    .Call('extraDistr_cpp_rdirichlet', PACKAGE = 'extraDistr', n, alpha)
}

cpp_ddnorm <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddnorm', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_ddunif <- function(x, min, max, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddunif', PACKAGE = 'extraDistr', x, min, max, log_prob)
}

cpp_pdunif <- function(x, min, max, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pdunif', PACKAGE = 'extraDistr', x, min, max, lower_tail, log_prob)
}

cpp_qdunif <- function(p, min, max, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qdunif', PACKAGE = 'extraDistr', p, min, max, lower_tail, log_prob)
}

cpp_rdunif <- function(n, min, max) {
    .Call('extraDistr_cpp_rdunif', PACKAGE = 'extraDistr', n, min, max)
}

cpp_ddweibull <- function(x, q, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddweibull', PACKAGE = 'extraDistr', x, q, beta, log_prob)
}

cpp_pdweibull <- function(x, q, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pdweibull', PACKAGE = 'extraDistr', x, q, beta, lower_tail, log_prob)
}

cpp_qdweibull <- function(p, q, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qdweibull', PACKAGE = 'extraDistr', p, q, beta, lower_tail, log_prob)
}

cpp_rdweibull <- function(n, q, beta) {
    .Call('extraDistr_cpp_rdweibull', PACKAGE = 'extraDistr', n, q, beta)
}

cpp_dfrechet <- function(x, lambda, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dfrechet', PACKAGE = 'extraDistr', x, lambda, mu, sigma, log_prob)
}

cpp_pfrechet <- function(x, lambda, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pfrechet', PACKAGE = 'extraDistr', x, lambda, mu, sigma, lower_tail, log_prob)
}

cpp_qfrechet <- function(p, lambda, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qfrechet', PACKAGE = 'extraDistr', p, lambda, mu, sigma, lower_tail, log_prob)
}

cpp_rfrechet <- function(n, lambda, mu, sigma) {
    .Call('extraDistr_cpp_rfrechet', PACKAGE = 'extraDistr', n, lambda, mu, sigma)
}

cpp_dgpois <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgpois', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_pgpois <- function(x, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgpois', PACKAGE = 'extraDistr', x, alpha, beta, lower_tail, log_prob)
}

cpp_rgpois <- function(n, alpha, beta) {
    .Call('extraDistr_cpp_rgpois', PACKAGE = 'extraDistr', n, alpha, beta)
}

cpp_dgev <- function(x, mu, sigma, xi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgev', PACKAGE = 'extraDistr', x, mu, sigma, xi, log_prob)
}

cpp_pgev <- function(x, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgev', PACKAGE = 'extraDistr', x, mu, sigma, xi, lower_tail, log_prob)
}

cpp_qgev <- function(p, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgev', PACKAGE = 'extraDistr', p, mu, sigma, xi, lower_tail, log_prob)
}

cpp_rgev <- function(n, mu, sigma, xi) {
    .Call('extraDistr_cpp_rgev', PACKAGE = 'extraDistr', n, mu, sigma, xi)
}

cpp_dgompertz <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgompertz', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_pgompertz <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgompertz', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qgompertz <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgompertz', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rgompertz <- function(n, a, b) {
    .Call('extraDistr_cpp_rgompertz', PACKAGE = 'extraDistr', n, a, b)
}

cpp_dgpd <- function(x, mu, sigma, xi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgpd', PACKAGE = 'extraDistr', x, mu, sigma, xi, log_prob)
}

cpp_pgpd <- function(x, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgpd', PACKAGE = 'extraDistr', x, mu, sigma, xi, lower_tail, log_prob)
}

cpp_qgpd <- function(p, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgpd', PACKAGE = 'extraDistr', p, mu, sigma, xi, lower_tail, log_prob)
}

cpp_rgpd <- function(n, mu, sigma, xi) {
    .Call('extraDistr_cpp_rgpd', PACKAGE = 'extraDistr', n, mu, sigma, xi)
}

cpp_dgumbel <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgumbel', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_pgumbel <- function(x, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgumbel', PACKAGE = 'extraDistr', x, mu, sigma, lower_tail, log_prob)
}

cpp_qgumbel <- function(p, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgumbel', PACKAGE = 'extraDistr', p, mu, sigma, lower_tail, log_prob)
}

cpp_rgumbel <- function(n, mu, sigma) {
    .Call('extraDistr_cpp_rgumbel', PACKAGE = 'extraDistr', n, mu, sigma)
}

cpp_dhalf <- function(x, nu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dhalf', PACKAGE = 'extraDistr', x, nu, sigma, log_prob)
}

cpp_phalf <- function(x, nu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_phalf', PACKAGE = 'extraDistr', x, nu, sigma, lower_tail, log_prob)
}

cpp_qhalf <- function(p, nu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qhalf', PACKAGE = 'extraDistr', p, nu, sigma, lower_tail, log_prob)
}

cpp_rhalf <- function(n, nu, sigma) {
    .Call('extraDistr_cpp_rhalf', PACKAGE = 'extraDistr', n, nu, sigma)
}

cpp_dhuber <- function(x, mu, sigma, epsilon, log_prob = FALSE) {
    .Call('extraDistr_cpp_dhuber', PACKAGE = 'extraDistr', x, mu, sigma, epsilon, log_prob)
}

cpp_phuber <- function(x, mu, sigma, epsilon, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_phuber', PACKAGE = 'extraDistr', x, mu, sigma, epsilon, lower_tail, log_prob)
}

cpp_qhuber <- function(p, mu, sigma, epsilon, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qhuber', PACKAGE = 'extraDistr', p, mu, sigma, epsilon, lower_tail, log_prob)
}

cpp_rhuber <- function(n, mu, sigma, epsilon) {
    .Call('extraDistr_cpp_rhuber', PACKAGE = 'extraDistr', n, mu, sigma, epsilon)
}

cpp_dinvgamma <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dinvgamma', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_dkumar <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dkumar', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_pkumar <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pkumar', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qkumar <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qkumar', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rkumar <- function(n, a, b) {
    .Call('extraDistr_cpp_rkumar', PACKAGE = 'extraDistr', n, a, b)
}

cpp_dlaplace <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlaplace', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_plaplace <- function(x, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plaplace', PACKAGE = 'extraDistr', x, mu, sigma, lower_tail, log_prob)
}

cpp_qlaplace <- function(p, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qlaplace', PACKAGE = 'extraDistr', p, mu, sigma, lower_tail, log_prob)
}

cpp_rlaplace <- function(n, mu, sigma) {
    .Call('extraDistr_cpp_rlaplace', PACKAGE = 'extraDistr', n, mu, sigma)
}

cpp_dlgser <- function(x, theta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlgser', PACKAGE = 'extraDistr', x, theta, log_prob)
}

cpp_plgser <- function(x, theta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plgser', PACKAGE = 'extraDistr', x, theta, lower_tail, log_prob)
}

cpp_qlgser <- function(p, theta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qlgser', PACKAGE = 'extraDistr', p, theta, lower_tail, log_prob)
}

cpp_rlgser <- function(n, theta) {
    .Call('extraDistr_cpp_rlgser', PACKAGE = 'extraDistr', n, theta)
}

cpp_dlomax <- function(x, lambda, kappa, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlomax', PACKAGE = 'extraDistr', x, lambda, kappa, log_prob)
}

cpp_plomax <- function(x, lambda, kappa, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plomax', PACKAGE = 'extraDistr', x, lambda, kappa, lower_tail, log_prob)
}

cpp_qlomax <- function(p, lambda, kappa, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qlomax', PACKAGE = 'extraDistr', p, lambda, kappa, lower_tail, log_prob)
}

cpp_rlomax <- function(n, lambda, kappa) {
    .Call('extraDistr_cpp_rlomax', PACKAGE = 'extraDistr', n, lambda, kappa)
}

cpp_dmnom <- function(x, size, prob, log_prob = FALSE) {
    .Call('extraDistr_cpp_dmnom', PACKAGE = 'extraDistr', x, size, prob, log_prob)
}

cpp_rmnom <- function(n, size, prob) {
    .Call('extraDistr_cpp_rmnom', PACKAGE = 'extraDistr', n, size, prob)
}

cpp_dmvhyper <- function(x, n, k, log_prob = FALSE) {
    .Call('extraDistr_cpp_dmvhyper', PACKAGE = 'extraDistr', x, n, k, log_prob)
}

cpp_rmvhyper <- function(nn, n, k) {
    .Call('extraDistr_cpp_rmvhyper', PACKAGE = 'extraDistr', nn, n, k)
}

cpp_dnst <- function(x, nu, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dnst', PACKAGE = 'extraDistr', x, nu, mu, sigma, log_prob)
}

cpp_pnst <- function(x, nu, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pnst', PACKAGE = 'extraDistr', x, nu, mu, sigma, lower_tail, log_prob)
}

cpp_qnst <- function(p, nu, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qnst', PACKAGE = 'extraDistr', p, nu, mu, sigma, lower_tail, log_prob)
}

cpp_rnst <- function(n, nu, mu, sigma) {
    .Call('extraDistr_cpp_rnst', PACKAGE = 'extraDistr', n, nu, mu, sigma)
}

cpp_dnsbeta <- function(x, alpha, beta, lower, upper, log_prob = FALSE) {
    .Call('extraDistr_cpp_dnsbeta', PACKAGE = 'extraDistr', x, alpha, beta, lower, upper, log_prob)
}

cpp_pnsbeta <- function(x, alpha, beta, lower, upper, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pnsbeta', PACKAGE = 'extraDistr', x, alpha, beta, lower, upper, lower_tail, log_prob)
}

cpp_qnsbeta <- function(p, alpha, beta, lower, upper, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qnsbeta', PACKAGE = 'extraDistr', p, alpha, beta, lower, upper, lower_tail, log_prob)
}

cpp_rnsbeta <- function(n, alpha, beta, lower, upper) {
    .Call('extraDistr_cpp_rnsbeta', PACKAGE = 'extraDistr', n, alpha, beta, lower, upper)
}

cpp_dpareto <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dpareto', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_ppareto <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ppareto', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qpareto <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qpareto', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rpareto <- function(n, a, b) {
    .Call('extraDistr_cpp_rpareto', PACKAGE = 'extraDistr', n, a, b)
}

cpp_dpower <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dpower', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_ppower <- function(x, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ppower', PACKAGE = 'extraDistr', x, alpha, beta, lower_tail, log_prob)
}

cpp_qpower <- function(p, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qpower', PACKAGE = 'extraDistr', p, alpha, beta, lower_tail, log_prob)
}

cpp_rpower <- function(n, alpha, beta) {
    .Call('extraDistr_cpp_rpower', PACKAGE = 'extraDistr', n, alpha, beta)
}

cpp_dprop <- function(x, size, mean, log_prob = FALSE) {
    .Call('extraDistr_cpp_dprop', PACKAGE = 'extraDistr', x, size, mean, log_prob)
}

cpp_pprop <- function(x, size, mean, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pprop', PACKAGE = 'extraDistr', x, size, mean, lower_tail, log_prob)
}

cpp_qprop <- function(p, size, mean, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qprop', PACKAGE = 'extraDistr', p, size, mean, lower_tail, log_prob)
}

cpp_rprop <- function(n, size, mean) {
    .Call('extraDistr_cpp_rprop', PACKAGE = 'extraDistr', n, size, mean)
}

cpp_drayleigh <- function(x, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_drayleigh', PACKAGE = 'extraDistr', x, sigma, log_prob)
}

cpp_prayleigh <- function(x, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_prayleigh', PACKAGE = 'extraDistr', x, sigma, lower_tail, log_prob)
}

cpp_qrayleigh <- function(p, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qrayleigh', PACKAGE = 'extraDistr', p, sigma, lower_tail, log_prob)
}

cpp_rrayleigh <- function(n, sigma) {
    .Call('extraDistr_cpp_rrayleigh', PACKAGE = 'extraDistr', n, sigma)
}

cpp_dskellam <- function(x, mu1, mu2, log_prob = FALSE) {
    .Call('extraDistr_cpp_dskellam', PACKAGE = 'extraDistr', x, mu1, mu2, log_prob)
}

cpp_rskellam <- function(n, mu1, mu2) {
    .Call('extraDistr_cpp_rskellam', PACKAGE = 'extraDistr', n, mu1, mu2)
}

cpp_dslash <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dslash', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_pslash <- function(x, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pslash', PACKAGE = 'extraDistr', x, mu, sigma, lower_tail, log_prob)
}

cpp_rslash <- function(n, mu, sigma) {
    .Call('extraDistr_cpp_rslash', PACKAGE = 'extraDistr', n, mu, sigma)
}

cpp_dtriang <- function(x, a, b, c, log_prob = FALSE) {
    .Call('extraDistr_cpp_dtriang', PACKAGE = 'extraDistr', x, a, b, c, log_prob)
}

cpp_ptriang <- function(x, a, b, c, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ptriang', PACKAGE = 'extraDistr', x, a, b, c, lower_tail, log_prob)
}

cpp_qtriang <- function(p, a, b, c, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qtriang', PACKAGE = 'extraDistr', p, a, b, c, lower_tail, log_prob)
}

cpp_rtriang <- function(n, a, b, c) {
    .Call('extraDistr_cpp_rtriang', PACKAGE = 'extraDistr', n, a, b, c)
}

cpp_dtnorm <- function(x, mu, sigma, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dtnorm', PACKAGE = 'extraDistr', x, mu, sigma, a, b, log_prob)
}

cpp_ptnorm <- function(x, mu, sigma, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ptnorm', PACKAGE = 'extraDistr', x, mu, sigma, a, b, lower_tail, log_prob)
}

cpp_qtnorm <- function(p, mu, sigma, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qtnorm', PACKAGE = 'extraDistr', p, mu, sigma, a, b, lower_tail, log_prob)
}

cpp_rtnorm <- function(n, mu, sigma, a, b) {
    .Call('extraDistr_cpp_rtnorm', PACKAGE = 'extraDistr', n, mu, sigma, a, b)
}

cpp_dwald <- function(x, mu, lambda, log_prob = FALSE) {
    .Call('extraDistr_cpp_dwald', PACKAGE = 'extraDistr', x, mu, lambda, log_prob)
}

cpp_pwald <- function(x, mu, lambda, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pwald', PACKAGE = 'extraDistr', x, mu, lambda, lower_tail, log_prob)
}

cpp_rwald <- function(n, mu, lambda) {
    .Call('extraDistr_cpp_rwald', PACKAGE = 'extraDistr', n, mu, lambda)
}

cpp_dzib <- function(x, size, prob, pi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dzib', PACKAGE = 'extraDistr', x, size, prob, pi, log_prob)
}

cpp_pzib <- function(x, size, prob, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pzib', PACKAGE = 'extraDistr', x, size, prob, pi, lower_tail, log_prob)
}

cpp_qzib <- function(p, size, prob, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qzib', PACKAGE = 'extraDistr', p, size, prob, pi, lower_tail, log_prob)
}

cpp_rzib <- function(n, size, prob, pi) {
    .Call('extraDistr_cpp_rzib', PACKAGE = 'extraDistr', n, size, prob, pi)
}

cpp_dzinb <- function(x, size, prob, pi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dzinb', PACKAGE = 'extraDistr', x, size, prob, pi, log_prob)
}

cpp_pzinb <- function(x, size, prob, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pzinb', PACKAGE = 'extraDistr', x, size, prob, pi, lower_tail, log_prob)
}

cpp_qzinb <- function(p, size, prob, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qzinb', PACKAGE = 'extraDistr', p, size, prob, pi, lower_tail, log_prob)
}

cpp_rzinb <- function(n, size, prob, pi) {
    .Call('extraDistr_cpp_rzinb', PACKAGE = 'extraDistr', n, size, prob, pi)
}

cpp_dzip <- function(x, lambda, pi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dzip', PACKAGE = 'extraDistr', x, lambda, pi, log_prob)
}

cpp_pzip <- function(x, lambda, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pzip', PACKAGE = 'extraDistr', x, lambda, pi, lower_tail, log_prob)
}

cpp_qzip <- function(p, lambda, pi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qzip', PACKAGE = 'extraDistr', p, lambda, pi, lower_tail, log_prob)
}

cpp_rzip <- function(n, lambda, pi) {
    .Call('extraDistr_cpp_rzip', PACKAGE = 'extraDistr', n, lambda, pi)
}

