# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dbbinom <- function(x, size, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, log_prob)
}

cpp_pbbinom <- function(x, size, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pbbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, lower_tail, log_prob)
}

cpp_rbbinom <- function(n, size, alpha, beta) {
    .Call('extraDistr_cpp_rbbinom', PACKAGE = 'extraDistr', n, size, alpha, beta)
}

cpp_dbnbinom <- function(x, size, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbnbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, log_prob)
}

cpp_pnbbinom <- function(x, size, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pnbbinom', PACKAGE = 'extraDistr', x, size, alpha, beta, lower_tail, log_prob)
}

cpp_rbnbinom <- function(n, size, alpha, beta) {
    .Call('extraDistr_cpp_rbnbinom', PACKAGE = 'extraDistr', n, size, alpha, beta)
}

cpp_dbnorm <- function(x, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, rho = 0, log_prob = FALSE) {
    .Call('extraDistr_cpp_dbnorm', PACKAGE = 'extraDistr', x, mu1, mu2, sigma1, sigma2, rho, log_prob)
}

cpp_pbnorm <- function(x, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, rho = 0, lower_tail = TRUE, log_prob = FALSE, nsim = 10000L) {
    .Call('extraDistr_cpp_pbnorm', PACKAGE = 'extraDistr', x, mu1, mu2, sigma1, sigma2, rho, lower_tail, log_prob, nsim)
}

cpp_rbnorm <- function(n, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, rho = 0) {
    .Call('extraDistr_cpp_rbnorm', PACKAGE = 'extraDistr', n, mu1, mu2, sigma1, sigma2, rho)
}

cpp_ddirichlet <- function(x, alpha, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddirichlet', PACKAGE = 'extraDistr', x, alpha, log_prob)
}

cpp_pdirichlet <- function(x, alpha, lower_tail = TRUE, log_prob = FALSE, nsim = 10000L) {
    .Call('extraDistr_cpp_pdirichlet', PACKAGE = 'extraDistr', x, alpha, lower_tail, log_prob, nsim)
}

cpp_rdirichlet <- function(n, alpha) {
    .Call('extraDistr_cpp_rdirichlet', PACKAGE = 'extraDistr', n, alpha)
}

cpp_ddweibull <- function(x, q, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_ddweibull', PACKAGE = 'extraDistr', x, q, beta, log_prob)
}

cpp_pdweibull <- function(x, q, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pdweibull', PACKAGE = 'extraDistr', x, q, beta, lower_tail, log_prob)
}

cpp_qdweibull <- function(p, q, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qdweibull', PACKAGE = 'extraDistr', p, q, beta, lower_tail, log_prob)
}

cpp_rdweibull <- function(n, q, beta) {
    .Call('extraDistr_cpp_rdweibull', PACKAGE = 'extraDistr', n, q, beta)
}

cpp_dfrechet <- function(x, lambda, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dfrechet', PACKAGE = 'extraDistr', x, lambda, mu, sigma, log_prob)
}

cpp_pfrechet <- function(x, lambda, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pfrechet', PACKAGE = 'extraDistr', x, lambda, mu, sigma, lower_tail, log_prob)
}

cpp_qfrechet <- function(p, lambda, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qfrechet', PACKAGE = 'extraDistr', p, lambda, mu, sigma, lower_tail, log_prob)
}

cpp_rfrechet <- function(n, lambda, mu, sigma) {
    .Call('extraDistr_cpp_rfrechet', PACKAGE = 'extraDistr', n, lambda, mu, sigma)
}

cpp_dgpois <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgpois', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_pgpois <- function(x, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgpois', PACKAGE = 'extraDistr', x, alpha, beta, lower_tail, log_prob)
}

cpp_rgpois <- function(n, alpha, beta) {
    .Call('extraDistr_cpp_rgpois', PACKAGE = 'extraDistr', n, alpha, beta)
}

cpp_dgev <- function(x, mu, sigma, xi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgev', PACKAGE = 'extraDistr', x, mu, sigma, xi, log_prob)
}

cpp_pgev <- function(x, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgev', PACKAGE = 'extraDistr', x, mu, sigma, xi, lower_tail, log_prob)
}

cpp_qgev <- function(p, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgev', PACKAGE = 'extraDistr', p, mu, sigma, xi, lower_tail, log_prob)
}

cpp_rgev <- function(n, mu, sigma, xi) {
    .Call('extraDistr_cpp_rgev', PACKAGE = 'extraDistr', n, mu, sigma, xi)
}

cpp_dgompertz <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgompertz', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_pgompertz <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgompertz', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qgompertz <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgompertz', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rgompertz <- function(n, a, b) {
    .Call('extraDistr_cpp_rgompertz', PACKAGE = 'extraDistr', n, a, b)
}

cpp_dgpd <- function(x, mu, sigma, xi, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgpd', PACKAGE = 'extraDistr', x, mu, sigma, xi, log_prob)
}

cpp_pgpd <- function(x, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgpd', PACKAGE = 'extraDistr', x, mu, sigma, xi, lower_tail, log_prob)
}

cpp_qgpd <- function(p, mu, sigma, xi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgpd', PACKAGE = 'extraDistr', p, mu, sigma, xi, lower_tail, log_prob)
}

cpp_rgpd <- function(n, mu, sigma, xi) {
    .Call('extraDistr_cpp_rgpd', PACKAGE = 'extraDistr', n, mu, sigma, xi)
}

cpp_dgumbel <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dgumbel', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_pgumbel <- function(x, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pgumbel', PACKAGE = 'extraDistr', x, mu, sigma, lower_tail, log_prob)
}

cpp_qgumbel <- function(p, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qgumbel', PACKAGE = 'extraDistr', p, mu, sigma, lower_tail, log_prob)
}

cpp_rgumbel <- function(n, mu, sigma) {
    .Call('extraDistr_cpp_rgumbel', PACKAGE = 'extraDistr', n, mu, sigma)
}

cpp_dinvgamma <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dinvgamma', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_pinvgamma <- function(x, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pinvgamma', PACKAGE = 'extraDistr', x, alpha, beta, lower_tail, log_prob)
}

cpp_rinvgamma <- function(n, alpha, beta) {
    .Call('extraDistr_cpp_rinvgamma', PACKAGE = 'extraDistr', n, alpha, beta)
}

cpp_dkumar <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dkumar', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_pkumar <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_pkumar', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qkumar <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qkumar', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rkumar <- function(n, a, b) {
    .Call('extraDistr_cpp_rkumar', PACKAGE = 'extraDistr', n, a, b)
}

cpp_dlaplace <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlaplace', PACKAGE = 'extraDistr', x, mu, sigma, log_prob)
}

cpp_plaplace <- function(x, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plaplace', PACKAGE = 'extraDistr', x, mu, sigma, lower_tail, log_prob)
}

cpp_qlaplace <- function(p, mu, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qlaplace', PACKAGE = 'extraDistr', p, mu, sigma, lower_tail, log_prob)
}

cpp_rlaplace <- function(n, mu, sigma) {
    .Call('extraDistr_cpp_rlaplace', PACKAGE = 'extraDistr', n, mu, sigma)
}

cpp_dlgser <- function(x, theta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlgser', PACKAGE = 'extraDistr', x, theta, log_prob)
}

cpp_plgser <- function(x, theta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plgser', PACKAGE = 'extraDistr', x, theta, lower_tail, log_prob)
}

cpp_rlgser <- function(n, theta) {
    .Call('extraDistr_cpp_rlgser', PACKAGE = 'extraDistr', n, theta)
}

cpp_dlomax <- function(x, lambda, kappa, log_prob = FALSE) {
    .Call('extraDistr_cpp_dlomax', PACKAGE = 'extraDistr', x, lambda, kappa, log_prob)
}

cpp_plomax <- function(x, lambda, kappa, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_plomax', PACKAGE = 'extraDistr', x, lambda, kappa, lower_tail, log_prob)
}

cpp_qlomax <- function(p, lambda, kappa, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qlomax', PACKAGE = 'extraDistr', p, lambda, kappa, lower_tail, log_prob)
}

cpp_rlomax <- function(n, lambda, kappa) {
    .Call('extraDistr_cpp_rlomax', PACKAGE = 'extraDistr', n, lambda, kappa)
}

cpp_dpareto <- function(x, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dpareto', PACKAGE = 'extraDistr', x, a, b, log_prob)
}

cpp_ppareto <- function(x, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ppareto', PACKAGE = 'extraDistr', x, a, b, lower_tail, log_prob)
}

cpp_qpareto <- function(p, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qpareto', PACKAGE = 'extraDistr', p, a, b, lower_tail, log_prob)
}

cpp_rpareto <- function(n, a, b) {
    .Call('extraDistr_cpp_rpareto', PACKAGE = 'extraDistr', n, a, b)
}

cpp_rpbinom <- function(n, prob) {
    .Call('extraDistr_cpp_rpbinom', PACKAGE = 'extraDistr', n, prob)
}

sim_dpbinom <- function(prob, nsim = 10000L) {
    .Call('extraDistr_sim_dpbinom', PACKAGE = 'extraDistr', prob, nsim)
}

rna_ppbinom <- function(prob) {
    .Call('extraDistr_rna_ppbinom', PACKAGE = 'extraDistr', prob)
}

cpp_dpower <- function(x, alpha, beta, log_prob = FALSE) {
    .Call('extraDistr_cpp_dpower', PACKAGE = 'extraDistr', x, alpha, beta, log_prob)
}

cpp_ppower <- function(x, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ppower', PACKAGE = 'extraDistr', x, alpha, beta, lower_tail, log_prob)
}

cpp_qpower <- function(p, alpha, beta, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qpower', PACKAGE = 'extraDistr', p, alpha, beta, lower_tail, log_prob)
}

cpp_rpower <- function(n, alpha, beta) {
    .Call('extraDistr_cpp_rpower', PACKAGE = 'extraDistr', n, alpha, beta)
}

cpp_drayleigh <- function(x, sigma, log_prob = FALSE) {
    .Call('extraDistr_cpp_drayleigh', PACKAGE = 'extraDistr', x, sigma, log_prob)
}

cpp_prayleigh <- function(x, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_prayleigh', PACKAGE = 'extraDistr', x, sigma, lower_tail, log_prob)
}

cpp_qrayleigh <- function(p, sigma, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qrayleigh', PACKAGE = 'extraDistr', p, sigma, lower_tail, log_prob)
}

cpp_rrayleigh <- function(n, sigma) {
    .Call('extraDistr_cpp_rrayleigh', PACKAGE = 'extraDistr', n, sigma)
}

cpp_dtriang <- function(x, a, b, c, log_prob = FALSE) {
    .Call('extraDistr_cpp_dtriang', PACKAGE = 'extraDistr', x, a, b, c, log_prob)
}

cpp_ptriang <- function(x, a, b, c, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ptriang', PACKAGE = 'extraDistr', x, a, b, c, lower_tail, log_prob)
}

cpp_qtriang <- function(p, a, b, c, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qtriang', PACKAGE = 'extraDistr', p, a, b, c, lower_tail, log_prob)
}

cpp_rtriang <- function(n, a, b, c) {
    .Call('extraDistr_cpp_rtriang', PACKAGE = 'extraDistr', n, a, b, c)
}

cpp_dtnorm <- function(x, mu, sigma, a, b, log_prob = FALSE) {
    .Call('extraDistr_cpp_dtnorm', PACKAGE = 'extraDistr', x, mu, sigma, a, b, log_prob)
}

cpp_ptnorm <- function(x, mu, sigma, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_ptnorm', PACKAGE = 'extraDistr', x, mu, sigma, a, b, lower_tail, log_prob)
}

cpp_qtnorm <- function(p, mu, sigma, a, b, lower_tail = TRUE, log_prob = FALSE) {
    .Call('extraDistr_cpp_qtnorm', PACKAGE = 'extraDistr', p, mu, sigma, a, b, lower_tail, log_prob)
}

cpp_rtnorm <- function(n, mu, sigma, a, b) {
    .Call('extraDistr_cpp_rtnorm', PACKAGE = 'extraDistr', n, mu, sigma, a, b)
}

